### ISSUE TITLE
Option 'since' is not optional

### ISSUE THREAD

**Issue by z3rone** [eHealthAfrica/download-email-attachments#12]
node version: v12.22.5
download-email-attachments version: 2.0.1

omitting the 'since'-option results in the following error:
```
Error: Search option argument must be a Date object or a parseable date string
    at buildSearchQuery (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:1911:21)
    at Connection._search (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:568:15)
    at Connection.search (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:557:8)
    at processMails (/home/user/newProject/node_modules/download-email-attachments/lib/find-emails.js:244:10)
    at /home/user/newProject/node_modules/download-email-attachments/lib/find-emails.js:155:7
    at Connection.<anonymous> (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:423:7)
    at Connection._resTagged (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:1521:22)
    at Parser.<anonymous> (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Connection.js:193:10)
    at Parser.emit (events.js:314:20)
    at Parser._resTagged (/home/user/newProject/node_modules/download-email-attachments/node_modules/imap/lib/Parser.js:175:10)
```

**Comment by z3rone** [comment]
project seems abandoned
